"""Otter: a modern dataframe library for clarity, correctness, and extensibility."""

from __future__ import annotations

from .dataframe import DataFrame
from .dtypes import (
    Boolean,
    Categorical,
    Date,
    Datetime,
    Decimal,
    DType,
    Duration,
    Float32,
    Float64,
    Int8,
    Int16,
    Int32,
    Int64,
    List,
    Null,
    Object,
    String,
    Struct,
    Time,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    can_cast,
    cast_value,
    cast_values,
    common_supertype,
    infer_dtype,
    is_numeric_dtype,
    is_string_dtype,
    is_temporal_dtype,
)
from .errors import (
    AggregationError,
    BackendError,
    CastError,
    ColumnNotFoundError,
    DTypeError,
    DataSourceError,
    DuplicateColumnError,
    ExpressionError,
    GroupByError,
    IndexError,
    InteropError,
    JoinError,
    LazyExecutionError,
    NullValueError,
    OtterError,
    ReshapeError,
    RowSelectionError,
    SchemaError,
    ShapeError,
    WindowError,
)
from .expressions import and_, col, lit, not_, or_
from .index import Index, RangeIndex
from .interop import from_arrow, from_numpy, from_pandas
from .io import read_csv, read_json, read_parquet, read_sql, write_csv, write_json, write_parquet
from .lazy import LazyFrame
from .nulls import NULL, NullValue, coalesce, is_null, normalize_null, not_null
from .schema import Field, Schema
from .series import Series
from .testing import assert_frame_equal, assert_schema_equal, assert_series_equal

__all__ = [
    "AggregationError",
    "BackendError",
    "Boolean",
    "CastError",
    "Categorical",
    "ColumnNotFoundError",
    "DType",
    "DTypeError",
    "DataFrame",
    "DataSourceError",
    "Date",
    "Datetime",
    "Decimal",
    "DuplicateColumnError",
    "Duration",
    "ExpressionError",
    "Field",
    "Float32",
    "Float64",
    "GroupByError",
    "Index",
    "IndexError",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "InteropError",
    "JoinError",
    "LazyExecutionError",
    "LazyFrame",
    "List",
    "NULL",
    "Null",
    "NullValue",
    "NullValueError",
    "Object",
    "OtterError",
    "RangeIndex",
    "ReshapeError",
    "RowSelectionError",
    "Schema",
    "SchemaError",
    "Series",
    "ShapeError",
    "String",
    "Struct",
    "Time",
    "UInt8",
    "UInt16",
    "UInt32",
    "UInt64",
    "WindowError",
    "and_",
    "assert_frame_equal",
    "assert_schema_equal",
    "assert_series_equal",
    "can_cast",
    "cast_value",
    "cast_values",
    "coalesce",
    "col",
    "common_supertype",
    "from_arrow",
    "from_numpy",
    "from_pandas",
    "infer_dtype",
    "is_null",
    "is_numeric_dtype",
    "is_string_dtype",
    "is_temporal_dtype",
    "lit",
    "normalize_null",
    "not_",
    "not_null",
    "or_",
    "read_csv",
    "read_json",
    "read_parquet",
    "read_sql",
    "write_csv",
    "write_json",
    "write_parquet",
]

__version__ = "0.1.0"
